export default function ObstetricauxTable() {
  return (
    <table className="obstetricaux-table">
      <tr>
        <td className="header-table">
          <span>Annee</span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
      </tr>
      <tr>
        <td className="header-table">
          <span>Accouchement a terme</span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
      </tr>
      <tr>
        <td className="header-table">
          <span>Accouchement premature</span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
      </tr>
      <tr>
        <td className="header-table">
          <span>ABRT spontane</span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
      </tr>
      <tr>
        <td className="header-table">
          <span>ABRT provoque</span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
      </tr>
      <tr>
        <td className="header-table">
          <span>MIU</span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
      </tr>
      <tr>
        <td className="header-table">
          <span>Mort-nes</span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
      </tr>
      <tr>
        <td className="header-table">
          <span>Deces neo-nataux</span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
        <td>
          <span></span>
        </td>
      </tr>
    </table>
  );
}
